version: '3'

services:
  nginx:
    build: ./docker/nginx
    ports:
      - ${APP_PORT}:80
    volumes:
      - .:${PROJECT_PATH}
      - ./docker/nginx/nginx.sh:/var/nginx.sh
      - ./docker/nginx/sites-enabled:/var/sites-enabled
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - PROJECT_PATH=${PROJECT_PATH}
    command: ./var/nginx.sh
  node: #Webpack server
    build: ./docker/node
    ports:
      - ${WEBPACK_DEV_SERVER_PORT}:${WEBPACK_DEV_SERVER_PORT}
    volumes:
      - .:${PROJECT_PATH}
    working_dir: ${PROJECT_PATH}
    command: "npm run dev"
